# Generated by Django 4.2.2 on 2023-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
