# Generated by Django 4.2.2 on 2023-06-07 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_create_date_alter_client_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 21, 48, 56, 934838, tzinfo=datetime.timezone.utc)),
        ),
    ]
