# Generated by Django 4.2.2 on 2023-06-07 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
