# Generated by Django 4.2.2 on 2023-06-07 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 7, 16, 59, 59, 793355)),
        ),
    ]
