# Generated by Django 4.2.2 on 2023-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_rename_create_date_client_create_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_d',
            field=models.CharField(max_length=50),
        ),
    ]
