# Generated by Django 4.2.2 on 2023-06-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_rename_create_d_client_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number_id',
            field=models.IntegerField(),
        ),
    ]
