# Generated by Django 4.2.2 on 2023-06-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
